### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ibbaMI** [bcgsc/ntJoin#65]
I got this error while runnin ntjoin:
Traceback (most recent call last):
  File "/home/pc/miniconda3/bin/share/ntjoin-1.0.6-1/bin/ntjoin_assemble.py", line 1125, in <module>
    main()
  File "/home/pc/miniconda3/bin/share/ntjoin-1.0.6-1/bin/ntjoin_assemble.py", line 1122, in main
    Ntjoin().main()
  File "/home/pc/miniconda3/bin/share/ntjoin-1.0.6-1/bin/ntjoin_assemble.py", line 1112, in main
    self.print_scaffolds(paths, intersecting_regions)
  File "/home/pc/miniconda3/bin/share/ntjoin-1.0.6-1/bin/ntjoin_assemble.py", line 910, in print_scaffolds
    missing_bed.saveas(self.args.p + "." + assembly + ".unassigned.bed")
  File "/home/pc/miniconda3/lib/python3.9/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/home/pc/miniconda3/lib/python3.9/site-packages/pybedtools/bedtool.py", line 3341, in saveas
    fn = self._collapse(
  File "/home/pc/miniconda3/lib/python3.9/site-packages/pybedtools/bedtool.py", line 1405, in _collapse
    with out_open_func(fn, "wt") as out_:
FileNotFoundError: [Errno 2] No such file or directory: 'out.k32.w500.n1./home/pc/Documents/RGF1/ragoo/rgf1.fa.k32.w500.tsv.unassigned.bed'
make: *** [/home/pc/miniconda3/bin/share/ntjoin-1.0.6-1/ntJoin:223: /home/pc/Documents/RGF1/ragoo/rgf1.fa.k32.w500.n1.assigned.scaffolds.fa] Error 1
make: *** Deleting file '/home/pc/Documents/RGF1/ragoo/rgf1.fa.k32.w500.n1.assigned.scaffolds.fa'

I run the test successfully.

Could you please help me resolving this issue?

Thank you in advance

**Comment by ibbaMI** [comment]
Problem solved,

it was a path file issue.

Raul

**Comment by lcoombe** [comment]
I'm glad you solved the issue @ibbaMI!
