### ISSUE TITLE
source file is in invalid format

### ISSUE THREAD

**Issue by Steven-Kemp** [bcgsc/ntJoin#71]
Hi Lauren,

I seem to be stumbling at the first instance here - see the below error:

ntjoin assemble target=G61HOA_scaffolds.fasta references=K12ecoli.fasta reference_weights='2' k=32 w=500 

/usr/local/Cellar/ntjoin/1.0.7/libexec/bin/src/indexlr --long --pos -k 32 -w 500 -t 4 K12ecoli.fasta > K12ecoli.fasta.k32.w500.tsv
[2021-09-01 17:10:54][ERROR] K12ecoli.fasta source file is in invalid format!
make: *** [K12ecoli.fasta.k32.w500.tsv] Error 1
make: *** Deleting file `K12ecoli.fasta.k32.w500.tsv'

can you advise on what is going wrong here? The reference is definitely in the correct fasta format...

Best wishes,
Steve

**Comment by lcoombe** [comment]
Hi Steve,

Is your reference fasta file multi-line? Double check that your fasta files are all single-line (ie. the sequence fully on a single line) - fasta files not being formatted in that way is the most common cause of that error. If needed, I like using a simple `seqtk seq` command to do the converison.

Hope that helps - thanks for your interest in ntJoin!
Lauren

**Comment by Steven-Kemp** [comment]
Hi Lauren,

Bingo! But now one other strange issue - python-igraph seems to have been deprecated as of today, so now I get this error:

----
ntjoin assemble target=single_120564_scaffolds.fasta references=single_K12ecoli.fasta reference_weights='2' k=32 w=500

/usr/local/Cellar/ntjoin/1.0.7/libexec/bin/bin/ntjoin_assemble.py -p out.k32.w500.n1 -n 1 -s single_120564_scaffolds.fasta.k32.w500.tsv -l 1 \
	-r "2" -k 32 -g 20 -G 0 -t 1 -m 90 single_K12ecoli.fasta.k32.w500.tsv
Traceback (most recent call last):
  File "/usr/local/Cellar/ntjoin/1.0.7/libexec/bin/bin/ntjoin_assemble.py", line 18, in <module>
    import igraph as ig
  File "/usr/local/Cellar/ntjoin/1.0.7/libexec/lib/python3.9/site-packages/igraph/__init__.py", line 34, in <module>
    from igraph._igraph import *
ModuleNotFoundError: No module named 'igraph._igraph'

---

when I open a python instance and attempt to import igraph, the follow message shows:

---
Deprecation notice
==================

To avoid name collision with the igraph project, the original igraph visualization
library has been renamed to `jgraph` in December 2015. The `igraph` package on
PyPI will soon be used by the igraph project.

The authors of `jgraph` (ex-igraph) and `python-igraph` (soon-to-be igraph)
project have agreed on a transition period during which old projects still
using `igraph` as a PyPI dependency will receive an error while trying to
import igraph in their own projects. The transition period ends on Sep 1 2021.

Things to do now
----------------

If you wanted to install the graph visualization library by Patrick Fuller,
please install `jgraph` instead. You have time until Sep 1 2021 to do this.

If you wanted to install the Python interface of the igraph network analysis
library, please install `python-igraph` instead. After Sep 1 2021, you can
start installing `igraph` instead. `python-igraph` will keep on working at
least until Sep 1 2022.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/steve/anaconda3/lib/python3.8/site-packages/igraph/__init__.py", line 8, in <module>
    warn_deprecation()
  File "/Users/steve/anaconda3/lib/python3.8/site-packages/igraph/_utils.py", line 36, in warn_deprecation
    raise RuntimeError("This package is deprecated. See the deprecation notice above.")
RuntimeError: This package is deprecated. See the deprecation notice above.
---

Please advise (sorry for the headache!).

Best wishes,
Steve

**Comment by lcoombe** [comment]
Hi Steve,

Hmm - that's a strange one. Can you confirm that you installed `python-igraph`? Not just`igraph`? I just made a fresh conda environment, and installed `python-igraph` - I couldn't replicate the issue..

```
conda create -n test
conda activate test
conda install python-igraph
```
```
(test) lcoombe03:assembly_demo lcoombe$ python
Python 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:36:15) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import igraph
>>> 
```

**Comment by lcoombe** [comment]
Hi Steve,

Excellent - I'm glad that you got it sorted out! 

All the best,
Lauren
