### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by SuPrSh** [bcgsc/ntJoin#76]
Hi,
I am constantly getting this error message when I try to run ntJoin. Will appreciate any help in this regard. 

ntJoin assemble target='/mnt/sdb/P6260/megahit/R1/final.contigs.fa' target_weight='1' references='singleline.ggan_v0.2.fa' reference_weights='2' w=500 t=32 mkt=True agp=True
/root/miniconda3/envs/ntjoin/bin/share/ntjoin-1.0.6-1/src/indexlr --long --pos -k 32 -w 500 -t 32 singleline.ggan_v0.2.fa > singleline.ggan_v0.2.fa.k32.w500.tsv
indexlr v1.2: Using more than 5 threads does not scale, reverting to 5.
/root/miniconda3/envs/ntjoin/bin/share/ntjoin-1.0.6-1/src/indexlr --long --pos -k 32 -w 500 -t 32 /mnt/sdb/P6260/megahit/R1/final.contigs.fa > /mnt/sdb/P6260/megahit/R1/final.contigs.fa.k32.w500.tsv
indexlr v1.2: Using more than 5 threads does not scale, reverting to 5.
samtools faidx singleline.ggan_v0.2.fa
/root/miniconda3/envs/ntjoin/bin/share/ntjoin-1.0.6-1/bin/ntjoin_assemble.py -p out.k32.w500.n1 -n 1 -s /mnt/sdb/P6260/megahit/R1/final.contigs.fa.k32.w500.tsv -l 1 \
-r "2" -k 32 -g 20 -G 0 -t 1 --mkt --agp singleline.ggan_v0.2.fa.k32.w500.tsv
Running ntJoin v1.0.6 ...

Parameters:
	Reference TSV files:  ['singleline.ggan_v0.2.fa.k32.w500.tsv']
	-s  /mnt/sdb/P6260/megahit/R1/final.contigs.fa.k32.w500.tsv
	-l  1.0
	-r  2
	-p  out.k32.w500.n1
	-n  1
	-k  32
	-g  20
	-G  0
	-t  1
	--agp
Orienting contigs with Mann-Kendall Test (more computationally intensive)

2021-09-26 14:51:07.256705 : Reading minimizers singleline.ggan_v0.2.fa.k32.w500.tsv
2021-09-26 14:51:22.589463 : Reading minimizers /mnt/sdb/P6260/megahit/R1/final.contigs.fa.k32.w500.tsv

Weights of assemblies:
singleline.ggan_v0.2.fa.k32.w500.tsv: 2.0
/mnt/sdb/P6260/megahit/R1/final.contigs.fa.k32.w500.tsv: 1.0

2021-09-26 14:51:40.034085 : Filtering minimizers
2021-09-26 14:51:54.872350 : Building graph
2021-09-26 14:52:30.235685 : Adding vertices
2021-09-26 14:52:31.290530 : Adding edges
2021-09-26 14:52:40.510767 : Adding attributes
2021-09-26 14:53:08.564395 : Printing graph out.k32.w500.n1.mx.dot

file_name	number	colour
singleline.ggan_v0.2.fa.k32.w500.tsv	0	red
/mnt/sdb/P6260/megahit/R1/final.contigs.fa.k32.w500.tsv	1	green

2021-09-26 14:53:42.022144 : Filtering the graph
2021-09-26 14:54:03.462824 : Reading fasta file /mnt/sdb/P6260/megahit/R1/final.contigs.fa
2021-09-26 14:54:06.828229 : Finding paths

Total number of components in graph: 9835 

2021-09-26 14:55:42.866699 : Printing output scaffolds
Traceback (most recent call last):
  File "/root/miniconda3/envs/ntjoin/bin/share/ntjoin-1.0.6-1/bin/ntjoin_assemble.py", line 1125, in <module>
    main()
  File "/root/miniconda3/envs/ntjoin/bin/share/ntjoin-1.0.6-1/bin/ntjoin_assemble.py", line 1122, in main
    Ntjoin().main()
  File "/root/miniconda3/envs/ntjoin/bin/share/ntjoin-1.0.6-1/bin/ntjoin_assemble.py", line 1112, in main
    self.print_scaffolds(paths, intersecting_regions)
  File "/root/miniconda3/envs/ntjoin/bin/share/ntjoin-1.0.6-1/bin/ntjoin_assemble.py", line 910, in print_scaffolds
    missing_bed.saveas(self.args.p + "." + assembly + ".unassigned.bed")
  File "/root/miniconda3/envs/ntjoin/lib/python3.8/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/root/miniconda3/envs/ntjoin/lib/python3.8/site-packages/pybedtools/bedtool.py", line 3341, in saveas
    fn = self._collapse(
  File "/root/miniconda3/envs/ntjoin/lib/python3.8/site-packages/pybedtools/bedtool.py", line 1405, in _collapse
    with out_open_func(fn, "wt") as out_:
FileNotFoundError: [Errno 2] No such file or directory: 'out.k32.w500.n1./mnt/sdb/P6260/megahit/R1/final.contigs.fa.k32.w500.tsv.unassigned.bed'
make: *** [/root/miniconda3/envs/ntjoin/bin/share/ntjoin-1.0.6-1/ntJoin:197: /mnt/sdb/P6260/megahit/R1/final.contigs.fa.k32.w500.n1.assigned.scaffolds.fa] Error 1
make: *** Deleting file '/mnt/sdb/P6260/megahit/R1/final.contigs.fa.k32.w500.n1.assigned.scaffolds.fa'
(ntjoin) root@nmcg:/mnt/sdb/P6260/ntJoin#  nohup ntJoin assemble target='/mnt/sdb/P6260/megahit/R1/final.contigs.fa' target_weight='1' references='singleline.ggan_v0.2.fa' reference_weights='2' w=500 t=32 mkt=True agp=True

Regards,
Surya

**Comment by lcoombe** [comment]
Hi Surya,

When launching ntJoin, ensure that all of the input files are in your current working directory - Or, as I usually do, create soft-links to your files in your current working directory. Then, when you launch the command, don't use an absolute path, like you have in your command for `target` currently. 
So, your command would end up looking something like this:

```
ntJoin assemble target='final.contigs.fa' target_weight='1' references='singleline.ggan_v0.2.fa' reference_weights='2' w=500 t=32 mkt=True agp=True
```

Hope that helps - thank you for your interest in ntJoin!
Lauren

**Comment by SuPrSh** [comment]
Thank you @lcoombe.Its working fine now.

**Comment by lcoombe** [comment]
Excellent - Glad it's working for you!
