### ISSUE TITLE
I found a big problem  in ntJoin script.

### ISSUE THREAD

**Issue by Shokusei** [bcgsc/ntJoin#84]
Hi, @lcoombe 
I want to use this software to scaffold the contigs obtained from the other genome assembler.
However, after typing the command "test_installation.sh" in the test directory, I found the following error message.

(RSEM) [iceplant4561@at138 tests]$ ./test_installation.sh
+ echo 'Running ntJoin...'
Running ntJoin...
+ ../ntJoin assemble target=scaf.f-f.fa target_weight=1 references=ref.fa reference_weights=2 prefix=f-f_test k=32 w=1000
/lustre7/home/iceplant4561/ntJoin/bin/ntjoin_assemble.py -p f-f_test -n 1 -s scaf.f-f.fa.k32.w1000.tsv -l 1 \
-r "2" -k 32 -g 20 -G 0 -t 1 -m 90 ref.fa.k32.w1000.tsv
Traceback (most recent call last):
  File "/lustre7/home/iceplant4561/ntJoin/bin/ntjoin_assemble.py", line 18, in <module>
    import pybedtools
  File "/home/iceplant4561/anaconda3/envs/RSEM/lib/python3.9/site-packages/pybedtools/__init__.py", line 16, in <module>
    from . import contrib
  File "/home/iceplant4561/anaconda3/envs/RSEM/lib/python3.9/site-packages/pybedtools/contrib/__init__.py", line 5, in <module>
    from .intersection_matrix import IntersectionMatrix
  File "/home/iceplant4561/anaconda3/envs/RSEM/lib/python3.9/site-packages/pybedtools/contrib/intersection_matrix.py", line 3, in <module>
    import sqlite3
  File "/home/iceplant4561/anaconda3/envs/RSEM/lib/python3.9/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/iceplant4561/anaconda3/envs/RSEM/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /home/iceplant4561/anaconda3/envs/RSEM/lib/python3.9/lib-dynload/_sqlite3.cpython-39-x86_64-linux-gnu.so: undefined symbol: sqlite3_errstr
make: *** [scaf.f-f.fa.k32.w1000.n1.assigned.scaffolds.fa] Error 1

I have asked my friend about this issue once. He said that I may use the other python object "/anaconda3/pkgs/sqlite-3.32.3-hcee41ef_1/lib/libsqlite3.so". 

Considering the above facts, I would like you to solve this problem!

**Comment by lcoombe** [comment]
Hi @Shokusei,

That looks like an issue with your `pybedtools` installation, which is a dependency of ntJoin. You can see that because the traceback is related to `import pybedtools`. It looks like you are using a conda environment, so my best first advice would be to create a fresh conda environment, and install the ntJoin dependencies there (or `conda install -c bioconda -c conda-forge ntjoin=1.0.8`.  You can then see whether pybedtools is working as expected by opening an interactive python session, and trying `import pybedtools`.

Do follow-up with more information if you have found an issue with ntJoin itself, versus the installation of a dependency. 

Thank you for your interest in ntJoin!
Lauren
